source "https://rubygems.org"

gem 'jekyll-assets'
gem 'jekyll-sitemap'
gem 'rake'
gem 'html-proofer'
gem 'sass'
gem 'autoprefixer-rails'
gem 'therubyracer'
gem 'uglifier'
gem 'jekyll-include-cache'

group :jekyll_plugins do
  gem 'jekyll-contentful-data-import','1.4.3'
  gem 'hawkins'
end
